.\" This file is part of Dconf Editor
.\"
.\" Dconf Editor is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" Dconf Editor is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with Dconf Editor.  If not, see <https://www.gnu.org/licenses/>.
.TH "DCONF\-EDITOR" "1"
.SH "NAME"
dconf-editor \- Graphical editor for gsettings and dconf
.SH "SYNOPSIS"
.B dconf\-editor [OPTIONS...]
.RE
.B dconf\-editor [OPTIONS...] [PATH]
.RE
.B dconf\-editor [OPTIONS...] [FIXED_SCHEMA | RELOCATABLE_SCHEMA:PATH] [KEY]
.SH "DESCRIPTION"
The
.B dconf\-editor
program provides a graphical interface for editing settings that are stored by other applications using the
.I gsettings
functions of the
.I glib
library, or in the
.I dconf
database. The
.BR gsettings (1)
and
.BR dconf (1)
utilities provides similar functionality on the commandline.
.SH "OPTIONS"
.TP
.BR \-h , \ \-\-help
Prints the command-line options and exits.
.TP
.BR \-v , \ \-\-version
Prints the release version and exits.
.TP
.BR \-\-list\-relocatable\-schemas
Prints the list of relocatable schemas and exits.
.TP
.BR \--I-understand-that-changing-options-can-break-applications
Launches application without showing initial warning.
.SH "SEE ALSO"
.BR dconf (7)
.BR dconf (1)
.BR gsettings (1)
